# Generated by Django 5.0.14 on 2026-09-13 21:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_quoterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAccessChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('code_hash', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(null=True)),
                ('last_sent', models.DateTimeField(null=True)),
                ('window_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('sends', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('html_message', models.TextField()),
                ('from_email', models.CharField(max_length=254)),
                ('recipients', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
