# Generated by Django 5.0.14 on 2026-09-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_bookingaccesschallenge_emaildelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildelivery',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
