[variables]
NIXPACKS_NO_DEFAULT_PORT = "true"

[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput --settings=tours_travels.settings_prod"
]

[start]
cmd = "python manage.py qcluster --settings=tours_travels.settings_prod"
